AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for Matragra Frontend Project
Parameters:
  BucketName:
    Type: String
    Default: 'matragra-frontend'
    Description: Name of the bucket to store this app
Resources:
  # ---Begin Frontend Resources---
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
Outputs:
  FrontendBucketARN:
    Value: !Sub ${FrontendBucket.Arn}